//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetflixTitles
{
    using System;
    using System.Collections.Generic;
    
    public partial class netflixTitle
    {
        public string show_id { get; set; }
        public string type { get; set; }
        public string title { get; set; }
        public string director { get; set; }
        public string cast { get; set; }
        public string country { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public int release_year { get; set; }
        public string rating { get; set; }
        public string duration { get; set; }
        public string listed_in { get; set; }
        public string description { get; set; }
    }
}
